version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet-service
    container_name: wallet-service-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - wallet-network

  db:
    image: postgres:12.19-alpine3.20
    container_name: wallet-service-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres_data:
